ratesCollector
LionnoiL/goit_bot pull request #22
Opened 2023-03-11 18:09 UTC by bit-to-bit

2023-03-11 19:34 UTC, shr3000 approved these changes

2023-03-11 20:20 UTC, LionnoiL requested changes

2023-03-11 20:20 UTC, LionnoiL commented on src/main/java/org/example/currency/services/CurrencyRateCollector.java
> +    );
це потрібно оформити як //TODO Сюди дописати усі сервіси для завантаження курсів з інших банків
тоді в ідеї його буде виділено

2023-03-11 20:20 UTC, LionnoiL commented on src/main/java/org/example/currency/services/CurrencyRateCollector.java
> +    );
Також вже є монобанк. потрібно оновити мейн та змержити ії з цією гілкою.

2023-03-11 21:59 UTC, bit-to-bit commented on src/main/java/org/example/currency/services/CurrencyRateCollector.java
> +    );
Додав MONOBANK в COLLECTOR. Однак під час тестування виявив, що сервіс MONOBANK повертає порожній  List. @MaksJavaDeveloper, подивишся, в чому справа?

2023-03-12 07:00 UTC, LionnoiL approved these changes

2023-03-12 07:01 UTC, merged