Додан функціонал зберігання налаштувань.
LionnoiL/goit_bot pull request #4
Opened 2023-03-08 17:33 UTC by LionnoiL

Змінений тип userId на long, т.я. ми отримуємо з телеграму long.
Додан private Map<Long, User> users в ApplicationProperties.
Додан UserService зі стандарними методами додавання, пошуку, видалення і т.п.
Список юзерів зберігається в users.json в корні.
Додавання нового юзера виконується на етапі розбору повідомлення в UserMessage.
Також в UserMessage додаеться знайдений юзер. Його можна використовувати в класах пакунку commands.

2023-03-08 17:57 UTC, AlexKii commented
а чому вирішив json в корень складати, а не в пропертіс?

2023-03-08 17:58 UTC, LionnoiL commented
Виправив опис пул реквесту. Файл users.json створюється в каталозі з ресурсами.

2023-03-09 09:54 UTC, TarasProrok approved these changes
ну, здається все гарно.

2023-03-09 10:13 UTC, LionnoiL commented on src/main/java/org/example/properties/ApplicationProperties.java
> +    static final String RESOURCES_PATH = "src/main/resources/";
В тебе в коді не буде отримання json. Ти будеш використовувати вже завантажений список юзерів. APPLICATION_PROPERTIES.getUsers.

2023-03-09 10:44 UTC, AlexKii commented on src/main/java/org/example/properties/ApplicationProperties.java
> +    static final String RESOURCES_PATH = "src/main/resources/";
ок
просто вчора не порозумілися
по я вже показував що читаю тестовий джісон і все працює
тоді буду працювати з мапою, якщо так краще

2023-03-09 10:47 UTC, AlexKii approved these changes

2023-03-09 10:57 UTC, AlexKii requested changes

2023-03-09 10:57 UTC, AlexKii commented on src/main/java/org/example/properties/ApplicationProperties.java
> +            savedUsers = new Gson().fromJson(fileReader, new TypeToken<Map<Integer, User>>() {
тут не лонг має бути, бо там зара інт зазначено?

2023-03-09 11:28 UTC, LionnoiL commented on src/main/java/org/example/properties/ApplicationProperties.java
> +            savedUsers = new Gson().fromJson(fileReader, new TypeToken<Map<Integer, User>>() {
так. дякую. зараз виправлю.

2023-03-09 12:19 UTC, merged