Add package banksExchangeRateUtils and files CurrencyRate, CurrencyRa…
LionnoiL/goit_bot pull request #9
Opened 2023-03-09 17:34 UTC by shr3000

…teService

2023-03-09 18:44 UTC, LionnoiL requested changes
чому не в пакеті currency? може краще в пакеті currency зробити пакет rates і туди все перенести.

2023-03-10 08:44 UTC, LionnoiL requested changes
з'явився другий пул реквест, де є цей самий клас тільки більш розширений. потрібно щоб ви домовились друг з другом кого лишаємо. я пропоную той другий але додати йому інтерфейс  CurrencyRateService

2023-03-10 10:07 UTC, LionnoiL requested changes
з'явився другий пул реквест, де є цей самий клас тільки більш розширений. потрібно щоб ви домовились друг з другом кого лишаємо. я пропоную той другий але додати йому інтерфейс  CurrencyRateService

2023-03-10 12:32 UTC, TarasProrok approved these changes

2023-03-10 19:19 UTC, bit-to-bit requested changes
Роман, подивись зауваження по класу

2023-03-10 19:19 UTC, bit-to-bit commented on src/main/java/org/example/banksExchangeRateUtils/CurrencyRate.java
> +
Пропоную використовувати мій клас, він більш розширений.

2023-03-11 08:37 UTC, shr3000 commented on src/main/java/org/example/banksExchangeRateUtils/CurrencyRate.java
> +
Згоден, але шо далі робити?

2023-03-11 08:37 UTC, shr3000 commented on src/main/java/org/example/banksExchangeRateUtils/CurrencyRate.java
> +
Ок. Як це зробити?

2023-03-11 08:57 UTC, bit-to-bit commented on src/main/java/org/example/banksExchangeRateUtils/CurrencyRate.java
> +
Андрій змерджив мою версію у гілку main, потрібно зробити pool собі на ПК з гілки main, потім налаштуватися на мій клас і зробити push на GitHub з урахуванням змін.

2023-03-11 09:45 UTC, LionnoiL commented on src/main/java/org/example/banksExchangeRateUtils/CurrencyRate.java
> +
Інтерфейс потрібно залишити тільки перенести його в пакунок rares. Він знадобиться.

2023-03-11 12:10 UTC, LionnoiL commented
Функціонал вже був доданий іншими.

2023-03-11 12:10 UTC, closed without merging